### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by siascone** [GIT-DS/kelp#3]
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
  - [x] primary key
  - [x] not null
  - [x] unique
  - [x] indexed
  - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
  - [x] schema is written in a table format
  - [x] the table’s name are lowercased, snake_cased and `back_ticked`
  - [x] the table header column names are bolded
  - [x] columns names are lowercased and snaked_cased and `back_ticked`

**Comment by siascone** [comment]
- table names should be lowercased and snaked cased
- missing bulleted info about tables (ex: indexed on, foreign keys etc.)

**Comment by siascone** [comment]
for your foreign key reference/association bullets you can simplify them
- `category_id` references `categories`

for all tables, any indexed column needs a description bullet indicating that index
- Indexed on `username`
- Indexed on `email`
- etc.

**Comment by GIT-DS** [comment]
@siascone i think i might've done everything. wasn't entirely sure if the table names are what comes before the separation lines

**Comment by siascone** [comment]
Looks pretty good. The only thing I would change for continuity is make your foreign key associations/references unique through out. You have 
- `foreign_key` references `table_name` 

for all table details except `business_categories` where you have 

- `foreign_key` is an association of the `x` table.
